Repository UMCreadme/Read_Me_Node.js, pull requests merged in 2024-08, with the labels that each got.

#40 :sparkles: [FEAT] #39 쇼츠 좋아요 기능 구현
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#34 :sparkles: [FEAT] #32: 쇼츠 댓글 생성 기능 구현
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#47 :bug: [Bug] #46 충돌 해결 중 생긴 오타 수정
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
Labels: :bug: bug

#41 ✨[FEAT] #38: 책 상세 정보(읽음 여부, 관련 쇼츠 리스트) 조회 구현
  config/error.js
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
  src/book/book.sql.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.dto.js
Labels: :sparkles: feature

#51 ✨ [FEAT} #50: 최근 검색어 리스트 반환
  index.js
  src/research/research.controller.js
  src/research/research.dao.js
  src/research/research.dto.js
  src/research/research.route.js
  src/research/research.service.js
  src/research/research.sql.js
Labels: :sparkles: feature

#55 ✨ [FEAT] #53: 최근 검색어 삭제
  src/research/research.controller.js
  src/research/research.dao.js
  src/research/research.route.js
  src/research/research.service.js
  src/research/research.sql.js
Labels: :sparkles: feature

#52 ✨[FEAT] #42, #45: 책 읽음 여부 업데이트 구현 & 알라딘 카테고리 <-> 리드미 카테고리 매핑 정보 반영
  config/response.status.js
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
  src/book/book.sql.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.service.js
Labels: :sparkles: feature

#43 ✨[FEAT] #21: 카카오 소셜 로그인 구현, jwt토큰을 통한 사용자 인증
  config/response.status.js
  package-lock.json
  package.json
  src/jwt/authJWT.js
  src/jwt/jwt-util.js
  src/jwt/refresh.js
  src/shorts/shorts.sql.js
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.dto.js
  src/users/users.route.js
  src/users/users.service.js
  src/users/users.sql.js
  yarn.lock
Labels: :sparkles: feature

#48 ✨ [FEAT] #44 최근 선택한 책 리스트 조회(쇼츠생성, 모임생성 시)
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.route.js
  src/book/book.service.js
  src/book/book.sql.js
Labels: :sparkles: feature

#63 :sparkles: [FEAT] #62: 최근 검색어 저장
  index.js
  src/home/home.sql.js
  src/research/research.controller.js
  src/research/research.dao.js
  src/research/research.route.js
  src/research/research.service.js
  src/research/research.sql.js
Labels: :sparkles: feature

#69 ♻️ [REFACTOR] #66: 유저 인가 필요한 부분 미들웨어 추가
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.route.js
  src/book/book.service.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
Labels: :sparkles: feature

#70 💚 [HOTFIX] 배포 포트 번호 수정
  .ebextensions/options.config
Labels: :bug: bug, :construction_worker: ci

#22 ✨[FEAT] #10: 커뮤니티 생성 구현
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/book/book.dao.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
  yarn.lock
Labels: :sparkles: feature

#82 🐛 bug(#80) : 데브 인덱스 고치기
  index.js
Labels: :bug: bug

#85 💚 [CI] #54: ELB 환경 이름 수정
  .github/workflows/deploy.yml
Labels: :bug: bug, :construction_worker: ci

#65 🐛 [bug]#64: 커뮤니티 조회 pageinfo 오류 수정
  config/pageInfo.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
Labels: :bug: bug

#83 ✨[FEAT] #71: 책 더미데이터 생성
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
Labels: :memo: docs, :sparkles: feature

#73 :sparkles: [FEAT] #68: 선호 카테고리 수정 기능 구현
  config/response.status.js
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.route.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#93 ✨ [FEAT] #92: 유저 읽은 책 권수 반환값에 추가
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.dto.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#95 ✨[FEAT] #94: 책 검색 api 및 최근 검색어 저장 기능 연결
  .github/workflows/deploy.yml
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
  src/book/book.sql.js
  src/common/common.dao.js
  src/home/home.dao.js
  src/home/home.dto.js
  src/home/home.sql.js
  src/research/research.controller.js
  src/research/research.dao.js
  src/research/research.route.js
  src/research/research.service.js
  src/research/research.sql.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.detail.dao.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
  src/users/users.controller.js
  src/users/users.dto.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#98 🐛 [FIX] 데이터베이스 커넥션 release 안 되는 문제 수정
  config/db.config.js
  src/book/book.controller.js
  src/book/book.dao.js
  src/common/common.dao.js
  src/communities/communities.dao.js
  src/home/home.dao.js
  src/research/research.dao.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.detail.dao.js
  src/users/users.dao.js
Labels: :bug: bug

#99 🚑 HOTFIX: 응답 코드 String으로 변경
  config/response.status.js
Labels: :bug: bug

#79 :sparkles: [FEAT] #76: 커뮤니티 삭제 구현
  config/response.status.js
  index.js
  package-lock.json
  package.json
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  yarn.lock
Labels: :sparkles: feature

#75 :sparkles: [FEAT] #74: 쇼츠 삭제 기능 구현
  config/response.status.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
Labels: :sparkles: feature

#103 🐛 [BUG] #102: 로그인 안한 회원이 유저 검색시 검색 기록 저장 불가
  src/users/users.service.js
Labels: :bug: bug

#105 🚑 [HOTFIX] 홈 화면 조회시 nullrefer 에러 수정
  src/home/home.dto.js
Labels: :bug: bug

#106 🚑 [HOTFIX] 메인 화면 정보 조회시 회원/비회원 별 카테고리 리스트 반환값 수정
  src/home/home.controller.js
  src/home/home.route.js
  src/home/home.service.js
Labels: :bug: bug

#101 ✨ [FEAT] #100: 책 검색시 미리보기용 검색일 경우 최근 검색어에 저장되지 않도록 수정
  src/book/book.controller.js
  src/book/book.service.js
  yarn.lock
Labels: :sparkles: feature

#84 ✨[FEAT] #67: 프로필 편집 기능 구현
  src/book/book.dao.js
  src/communities/communities.dao.js
  src/home/home.dao.js
  src/jwt/jwt-util.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.detail.dao.js
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.route.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#33 ✨[FEAT] #31: 커뮤니티 검색 기능 구현
  config/response.status.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
Labels: :sparkles: feature

#113 ✨ [FEAT] #112: 책 상세 정보 조회시 책 관련 정보도 같이 넘겨주도록 수정
  config/response.status.js
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
  src/research/research.sql.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.service.js
Labels: :sparkles: feature

#115 🐛 [BUG] #114: 최근 선택한 책 리스트 조회에 쇼츠아이디 순 추가
  src/book/book.sql.js
Labels: :bug: bug

#118 🐛 [BUG] #116: 쇼츠 상세 정보 조회 로직 수정
  src/book/book.service.js
  src/common/common.algorithm.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.detail.dao.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
  src/users/users.service.js
Labels: :bug: bug, :sparkles: feature

#119 🐛 [HOTFIX] : 메인 화면 추천탭 조회시 유저가 선호하는 카테고리의 인기 쇼츠 조회 sql문 수정
  src/home/home.dao.js
  src/home/home.sql.js
  src/shorts/shorts.detail.dao.js
Labels: :bug: bug

#117 ✨[FEAT] #107: 커뮤니티 전반적인 수정+커뮤니티 상세정보 조회+채팅방 조회+약속설정
  config/response.status.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
Labels: :sparkles: feature

#96 ✨[FEAT] #78: 내 채팅방 조회 기능 구현
  src/book/book.dto.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
Labels: :sparkles: feature

#129 🚑 [HOTFIX] #78: 누락된 쿼리문 추가
  src/communities/communities.dao.js
  src/communities/communities.sql.js
Labels: :bug: bug

#104 ✨[FEAT] #49: 채팅 기능 구현
  config/response.status.js
  config/socketServer.js
  index.js
  package-lock.json
  package.json
  public/chat.css
  public/chat.js
  public/index.html
  src/book/book.dao.js
  src/chat/chat.controller.js
  src/chat/chat.dao.js
  src/chat/chat.dto.js
  src/chat/chat.route.js
  src/chat/chat.service.js
  src/chat/chat.sql.js
  yarn.lock
Labels: :sparkles: feature

#126 🐛 [HOTFIX] 업로드 파일 용량 제한 30M로 설정
  .platform/nginx/nginx.conf
Labels: :bug: bug, :sparkles: feature

#130 🐛 [HOTFIX] #78: 커뮤니티 충돌 문제 수정
  config/response.status.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
Labels: :bug: bug

#137 :bug: [!HOTFIX] pharse 좌표값 반환하도록 수정
  src/home/home.dto.js
  src/home/home.sql.js
Labels: :bug: bug

#139 :sparkles: [FEAT] #138: 쇼츠 댓글 리스트 조회 구현
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#128 ✨[FEAT] #127: 쇼츠 검색시 반환되는 데이터 수정
  src/book/book.controller.js
  src/home/home.dto.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#142 🐛 [!HOTFIX] #141 : 팔로우 취소 기능 응답 오류 수정
  src/users/users.service.js
Labels: :bug: bug

#143 🐛 [!HOTFIX] #140: 메인화면 카테고리탭 조회에서 유저인가 부분 추가 및 쿼리문 수정
  src/home/home.controller.js
  src/home/home.dao.js
  src/home/home.dto.js
  src/home/home.route.js
  src/home/home.service.js
  src/home/home.sql.js
Labels: :bug: bug

#149 🐛 [!HOTFIX] #148: 유저가 읽은 책 리스트 조회시 book_id 값 제대로 반환
  src/users/users.dto.js
Labels: :bug: bug

#147 🐛 [!HOTFIX] #146: 쇼츠 댓글 작성시 쇼츠 댓글리스트 전체 반환(페이징없이)
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :bug: bug

#153 🐛 [!HOTFIX] #152: 메인화면 피드 리스트 수정
  src/home/home.sql.js
Labels: :bug: bug

#158 🐛 [!HOTFIX] #155: 쇼츠검색 응답 닉네임을 어카운트로 수정
  src/shorts/shorts.dto.js
Labels: :bug: bug

#157 🐛[!HOTFIX] #156: 메인화면 피드에서 유저 정보 반환 수정
  src/home/home.dto.js
  src/home/home.sql.js
Labels: :bug: bug

#165 🐛 [!HOTFIX] #164 : 모임 상세, 그룹 채팅방에서 해시태그 앞 # 붙여 보내기
  src/communities/communities.dto.js
Labels: :bug: bug

#168 🐛 [HOTFIX] 좋아요, 댓글 수 조회 sql 쿼리 수정
  src/home/home.controller.js
  src/home/home.sql.js
Labels: :bug: bug
