Repository UMCreadme/Read_Me_Node.js, pull requests merged in 2024-07, with the labels that each got.

#5 ✨[FEAT] #2: 유저 정보 조회, 유저가 만든 쇼츠 리스트 페이징 조회 구현
  config/response.js
  index.js
  package-lock.json
  src/book/book.dao.js
  src/book/book.sql.js
  src/shorts/shorts.sql.js
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.dto.js
  src/users/users.route.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#9 ✨[FEAT] #6: 경로별 라우팅 세팅, 도메인에 맞게 펑션 분리
  index.js
  src/book/book.controller.js
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.route.js
  src/book/book.service.js
  src/book/book.sql.js
  src/group/group.controller.js
  src/group/group.dao.js
  src/group/group.dto.js
  src/group/group.route.js
  src/group/group.service.js
  src/group/group.sql.js
  src/home/home.controller.js
  src/home/home.dao.js
  src/home/home.dto.js
  src/home/home.route.js
  src/home/home.service.js
  src/home/home.sql.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.detail.dao.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
  src/users/users.controller.js
  src/users/users.dao.js
  src/users/users.dto.js
  src/users/users.route.js
  src/users/users.service.js
  src/users/users.sql.js
Labels: :sparkles: feature

#12 ✨[FEAT] #7: 쇼츠 검색 기능 구현
  src/book/book.dao.js
  src/book/book.sql.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#14 ✨[FEAT] #1: 검색 > 쇼츠 상세 정보 조회 기능 + 기존 로직 일부 수정
  config/error.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.detail.dao.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/shorts/shorts.sql.js
Labels: :sparkles: feature

#20 ✨[FEAT] #18: 쇼츠 생성 기능 구현
  config/response.status.js
  config/s3.manager.js
  package-lock.json
  package.json
  src/book/book.dao.js
  src/book/book.dto.js
  src/book/book.sql.js
  src/common/common.dao.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.dao.js
  src/shorts/shorts.dto.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/test/test.route.js
Labels: :sparkles: feature

#23 ✨ [FEAT] #16: 메인 화면 카테고리탭 정보 조회 구현
  index.js
  package-lock.json
  package.json
  src/home/home.controller.js
  src/home/home.dao.js
  src/home/home.dto.js
  src/home/home.route.js
  src/home/home.service.js
  src/home/home.sql.js
  yarn.lock
Labels: :sparkles: feature

#25 ✨[FEAT] #24: 커뮤니티 조회 구현
  index.js
  src/communities/communities.controllers.js
  src/communities/communities.dao.js
  src/communities/communities.dto.js
  src/communities/communities.route.js
  src/communities/communities.service.js
  src/communities/communities.sql.js
  src/group/group.controller.js
  src/group/group.dao.js
  src/group/group.dto.js
  src/group/group.route.js
  src/group/group.service.js
  src/group/group.sql.js
Labels: :sparkles: feature

#37 🐛 [BUG] #19: 쇼츠 상세 조회 API 에러 처리 추가
  src/shorts/shorts.detail.dao.js
  src/shorts/shorts.detail.sql.js
  src/shorts/shorts.sql.js
Labels: :bug: bug

#36 ✨[FEAT] #28: 전역 에러 핸들링 상황 테스트 구현
  index.js
  src/shorts/shorts.controller.js
  src/shorts/shorts.route.js
  src/shorts/shorts.service.js
  src/test/test.controllers.js
  src/test/test.dao.js
  src/test/test.route.js
  src/test/test.service.js
Labels: :bug: bug, :sparkles: feature
